Dumbass me implementing some stuff I wanted to have but didn't want to implement until now

diff --git a/bin/.local/bin/lyrics_extractor b/bin/.local/bin/lyrics_extractor
--- a/bin/.local/bin/lyrics_extractor
+++ b/bin/.local/bin/lyrics_extractor
@@ -4,9 +4,30 @@ pushd . || exit 10
 
 lyrics_dir="$HOME/.lyrics"
 
-find . -type f \( -iname "*.mp3" -o -iname "*.flac" -o -iname "*.wav" \) | while read -r file; do
-  artist="$(ffprobe -i "$file" -print_format json -show_format 2>/dev/null | jq -r '.format.tags.artist // empty')"
-  title="$(ffprobe -i "$file" -print_format json -show_format 2>/dev/null | jq -r '.format.tags.title // empty')"
+get_artist () {
+  printf "%s" "$(ffprobe -i "$1" -print_format json -show_format 2>/dev/null | jq -r '.format.tags.artist // empty')"
+}
+
+get_title () {
+  printf "%s" "$(ffprobe -i "$1" -print_format json -show_format 2>/dev/null | jq -r '.format.tags.title // empty')"
+}
+
+fetch_lyrics () {
+
+  local song
+
+  if [ ! "$file" ]; then
+    if [ ! "$1" ]; then
+      echo "Error: Could not extract artist or title from the file."
+      exit 1
+    fi
+    song="$1"
+  else
+    song="$file"
+  fi
+
+  artist=$(get_artist "$song")
+  title=$(get_title "$song")
 
   if [ -z "$artist" ] || [ -z "$title" ]; then
     echo "Error: Could not extract artist or title from the file."
@@ -15,9 +36,19 @@ find . -type f \( -iname "*.mp3" -o -iname "*.flac" -o -iname "*.wav" \) | while
 
   filename="${artist} - ${title}.txt"
 
-  ffprobe -i "$file" -print_format json -show_format 2> /dev/null | jq -r '.format.tags | to_entries[] | select(.key | startswith("lyrics-")) .value' > "$lyrics_dir/$filename"
+  ffprobe -i "$song" -print_format json -show_format 2> /dev/null | \
+    jq -r '.format.tags | to_entries[] | select(.key | startswith("lyrics-")) .value' > "$lyrics_dir/$filename"
 
   echo "Extracted lyrics for ${filename/.txt/}"
-done
+}
+
+
+if [ ! "$1" ]; then
+  find . -type f \( -iname "*.mp3" -o -iname "*.flac" -o -iname "*.wav" \) | while read -r file; do
+    fetch_lyrics "$file"
+  done
+else
+  fetch_lyrics "$1"
+fi
 
 popd || exit 10
